# Generated by Django 3.1.4 on 2021-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0002_auto_20210106_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
