# Generated by Django 3.1.4 on 2021-01-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0004_auto_20210106_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='slug',
        ),
    ]
